id: resmpd
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    containers:
      - name: resmpd-test
        image: gcr.io/resm_sketch/gcloud-resm
        ports:
          - hostPort: 80
            containerPort: 9090
#labels:
#  name: "resmpd-test"
